---
title: "EffortGraph"
author: "Matthew Warham"
date: "March 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(tidyverse)
library(janitor)
library(broom)
library(reshape2)



effortresults <- read.csv("tons.csv")

View(effortresults)


  
  
  
                  

```

```{r}

priceresults <- read.csv("price.csv")

View(priceresults)

ggplot(priceresults) +
  geom_line(aes(Tonnes, Price), color = "black", size = 2) +
  geom_segment(aes( x = 0, xend= Inf, y = 67.5, yend = 67.5), linetype = "dashed", color = "red")+
  geom_segment(aes( x = 0, xend= Inf, y = 37.5, yend = 37.5), linetype = "dashed", color = "red")+
  geom_segment(aes( x = 0, xend= Inf, y = 7.5, yend = 7.5), linetype = "dashed", color = "red")+
  annotate("text", x = 6, y = 70, label = "25% Reduction in Effort", size = 3, family = "Century Gothic") +
  annotate("text", x = 4, y = 40, label = "50% Reduction in Effort", size = 3, family = "Century Gothic") +
  annotate("text", x = 6.5, y = 10, label = "90% Reduction in Effort", size = 3, family = "Century Gothic") +
  scale_x_continuous(expand = c(0,0), limits = c(0,15))+
  scale_y_continuous(expand = c(0,0), limits = c(0,75))+
  labs( x = "Tonnes of Aquaculture", y = "Price (USD)")+
  ggtitle("Fish Money")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))


```

