---
title: "Simulating Economic and Ecological Outcomes of Totoaba Aquaculture"
output:
html_document: default
---

####0. Libraries

```{r libraries, warning = FALSE, error = FALSE, message = FALSE}

#  Watch out for plyr-dplyr conflict in loading.
#library(devtools)
#install_github("vqv/ggbiplot") # For updates to ggbiplot development.
library(plyr) # Fixing plyr loading after dplyr in vis.R.
library(knitr)
library(tidyverse)
library(janitor)
library(broom)
library(reshape2)
library(ggpubr)
library(ggbiplot)
library(factoextra)

```

####1. Data

```{r dat_read, cache = FALSE}
knitr::read_chunk('./scripts/dat.R')
```

```{r dat}
```

####2. Functions

```{r fun_read}

knitr::read_chunk('./scripts/fun.R')

```

```{r fun}
```

####3. Set-Up

```{r set_read}

knitr::read_chunk('./scripts/set.R')

```

```{r set}
```


####5. Runs

```{r run_read}
knitr::read_chunk('./scripts/run.R')
```

```{r run}
```

####6. Analysis and Visualization

#####6.1 Biomass
```{r bio_read}
knitr::read_chunk('./scripts/bio.R')
```

```{r bio}
```

#####6.2 Profit
```{r pi_read}
knitr::read_chunk('./scripts/pi.R')
```

```{r pi}
```

#####6.3 Demand
```{r dem_read}
knitr::read_chunk('./scripts/dem.R')
```

```{r vis}
```

#####6.4 PCA
```{r pca_read}
knitr::read_chunk('./scripts/pca.R')
```

```{r pca}
```

#####6.5 Map
```{r map_read}
knitr::read_chunk('./scripts/map.R')
```

```{r map}
```